### ISSUE TITLE
A connection to the server could not be established. (18.9d7a7b5c.1629394601.74c28a78)

### ISSUE THREAD

**Issue by GrumpyCatastrophe** [FriendsOfGalaxy/galaxy-integration-psn#30] opened 2021-08-19 17:55 UTC
When trying to connect using new version of the plugin (0.34), after passing Mouse & Cheese verification, there is an error:
`A connection to the server could not be established.
(18.9d7a7b5c.1629394601.74c28a78)`

Multiple tries and Galaxy restart does not help at all, but is changing few last digits in the error number. Everything was working fine on previous versions before MyPlaystation was closed. 

Error is appearing in the moment in which 2FA should be triggered, so it could mean 2FA is no longer supported by the plugin. Is new version of plugin working for anyone with 2FA?

I am not the only person getting that problem: https://www.reddit.com/r/gog/comments/p7ane5/psn_integration_working_again/h9iuywb/?utm_source=reddit&utm_medium=web2x&context=3

In logs there is nothing about what happens after initial window for credentials is opened.
[psn-logs.log](https://github.com/FriendsOfGalaxy/galaxy-integration-psn/files/7016760/psn-logs.log)

**Comment by Fikus25** [comment] 2021-08-19 21:29
Same problem here. Multiple hard logic puzzles solved but everytime same error message.

**Comment by AlJoelson** [comment] 2021-08-20 00:48
Ditto.

**Comment by joyrider3774** [comment] 2021-08-20 13:29
i have this problem also yes, erasing everything from galaxy and the plugin does not help either. It could be some "bot" detection playstation is doing and maybe they have flagged galaxy or the plugin. I have not tried to see if i could change the user agent somewhere to see if it would solve it

**Comment by UnperfectOne** [comment] 2021-08-20 23:52
I can confirm I'm having this issue as well. I tried multiple times before and after updating GOG Galaxy to no avail.

**Comment by Dicion** [comment] 2021-08-22 18:13
Confirm I have this same issue today.

I can login in a browser fine. Trying via GOG makes me do 2 logic puzzles, followed by an error.

**Comment by FriendsOfGalaxy** [comment] 2021-08-23 11:44
Hi, the issue is known and the most probable reason is anty-bot detection on Sony side. 

I'm closing as a duplicate of this one: https://github.com/FriendsOfGalaxy/galaxy-integration-psn/issues/7

**Closed as completed by FriendsOfGalaxy** 2021-08-23 11:44 UTC
