### ISSUE TITLE
Playstation integration in GOG 2.0 not working

### ISSUE THREAD

**Issue by OmegaSelvatico** [FriendsOfGalaxy/galaxy-integration-psn#32] opened 2021-09-02 12:41 UTC
Hello I found a strange error while I'm trying to connect the Playstation integration through your portal. When I click on "Connect", a blank page opens with the following message:

{"error_code":4151,"error":"unauthorized_client","error_description":"Client does not have grant type: [\"implicit\",\"authorization_code\"]","docs":"http://central-auth.p1-np-eib.prod.navcloud.sonynei.net/docs/#api/centralauthservice/v1/oauth/authorize/get"}

Is the problem on my side of the computer or there's a glitch about the integration?
If it helps, I'm trying to connect the same portal through Gamenite, but the PSN page can't log me in, as if my account never existed, even though when I try to log in the PSN website with the same details, it let me through with no problem.
![gog](https://user-images.githubusercontent.com/34311633/131845160-ed35e3c4-5560-451b-b489-3d0d4affe043.jpg)

**Comment by ManemanFTW** [comment] 2021-09-02 17:52
This is similar to what happened here #25

**Comment by mika76** [comment] 2021-09-05 07:24
Same issue - can't connect.

**Comment by OmegaSelvatico** [comment] 2021-09-08 14:19
I see. I understand that the issue is well known, but still needs to be corrected, am I right?

**Comment by callmekoo** [comment] 2021-09-08 20:37
No, the problem is fixed in #25. You just need to update PSN integration plugin.

**Comment by mika76** [comment] 2021-09-09 06:49
Mine works now

**Comment by OmegaSelvatico** [comment] 2021-09-10 16:07
> No, the problem is fixed in #25. You just need to update PSN integration plugin.

Oh, really? Sorry, I didn't quite understand where to look at properly through those comments in the specific and... had no time in these days to study the whole topic. I know, I'm ignorant, first time I'm interacting with this forum. I'll go look for sure!

**Closed as completed** 2021-09-10 16:22 UTC
